<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::insert([
            [   
                'usertype'      => 'admin',
                'firstname'     => 'Rhannel',
                'middlename'    => 'Dalida',
                'lastname'      => 'Dinlasan',
                'gender'        => 'male',
                'religion'      => 'Roman Catholic',
                'birthday'      => '1999-12-07',
                'birthplace'    => 'Biga, Calatagan, Batangas',
                'address'       => 'Biga, Calatagan, Batangas',
                'phone'         => '09351458776',
                'email'         => 'rhannel.dinlasan@g.batstate-u.edu.ph',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'officer',
                'firstname'     => 'Hazel',
                'middlename'    => 'Gal',
                'lastname'      => 'Gonzales',
                'gender'        => 'female',
                'religion'      => 'Roman Catholic',
                'birthday'      => '1999-10-23',
                'birthplace'    => 'Tanagan, Calatagan, Batangas',
                'address'       => 'Tanagan, Calatagan, Batangas',
                'phone'         => '09664554812',
                'email'         => 'hazel.gonzales@g.batstate-u.edu.ph',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'scholar',
                'firstname'     => 'John Raven',
                'middlename'    => 'Rodriguez',
                'lastname'      => 'Balbar',
                'gender'        => 'male',
                'religion'      => 'Roman Catholic',
                'birthday'      => '2000-09-17',
                'birthplace'    => 'Cumba, Lian , Batangas',
                'address'       => 'Cumba, Lian , Batangas',
                'phone'         => '09664250790',
                'email'         => 'johnraven.balbar@g.batstate-u.edu.ph',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
        ]);

        $scholars = array(
            array('firstname' => 'Ren','middlename' => 'Eroles','lastname' => 'Dalida','gender' => 'male','address' => 'Biga, Calatagan, Batangas','birthplace' => 'Biga, Calatagan, Batangas','phone' => '09664251790','email' => 'rendalida@g.batstate-u.edu.ph'),
            array('firstname' => 'Alzeo','middlename' => 'Togonon','lastname' => 'Landicho','gender' => 'male','address' => 'Matabungkay Lian Batangas','birthplace' => 'Matabungkay Lian Batangas','phone' => '9478295181','email' => 'alzeo.landicho.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Alvin','middlename' => 'Dimaala','lastname' => 'Dalida','gender' => 'male','address' => 'Bucana Nasugbu Batangas','birthplace' => 'Bucana Nasugbu Batangas','phone' => '9142366532','email' => 'alvin.dalida.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Analy','middlename' => 'Cuadra','lastname' => 'Dalida','gender' => 'female','address' => 'Barangay 4, Nasugbu Batangas','birthplace' => 'Barangay 4, Nasugbu Batangas','phone' => '9234627346','email' => 'analy.dalida.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jaypee','middlename' => 'Conocido','lastname' => 'Venzon','gender' => 'male','address' => 'Puting kahoy Lian Batangas','birthplace' => 'Puting kahoy Lian Batangas','phone' => '9627237462','email' => 'jaypee.venzon.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Daisy','middlename' => 'Barangas','lastname' => 'Elposar','gender' => 'male','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9674572347','email' => 'daisy.elposar.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Nikki Sofia','middlename' => 'Lopez','lastname' => 'Mailig','gender' => 'female','address' => 'Baragay 7, Nasugbu Batangas','birthplace' => 'Baragay 7, Nasugbu Batangas','phone' => '9656892304','email' => 'nikkisofia.mailig.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ryan','middlename' => 'Tanilon','lastname' => 'De Luna','gender' => 'male','address' => 'Baragay 7, Nasugbu Batangas','birthplace' => 'Baragay 7, Nasugbu Batangas','phone' => '9523423404','email' => 'ryan.deluna.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jayrald','middlename' => 'Dimaala','lastname' => 'Holgado','gender' => 'male','address' => 'Poblacion 3, Calatagan Batangas','birthplace' => 'Poblacion 3, Calatagan Batangas','phone' => '9342376434','email' => 'jayrald.holgado.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ian Glenn','middlename' => 'Togonon','lastname' => 'Mercado','gender' => 'male','address' => 'Barangay 4 Nasugbu Batangas','birthplace' => 'Barangay 4 Nasugbu Batangas','phone' => '9180917030','email' => 'ianglenn.mercado.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Judith','middlename' => 'Macalalad','lastname' => 'Manalo','gender' => 'female','address' => 'Balibago, Calatagan Batangas','birthplace' => 'Balibago, Calatagan Batangas','phone' => '9463126241','email' => 'judith.manalo.example@g.batstate-u.edu.ph'),
            array('firstname' => 'John Paul','middlename' => 'Macalindong','lastname' => 'Macalindong','gender' => 'male','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9915347221','email' => 'johnpaul.macalindong.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ronniel','middlename' => 'Hernandez','lastname' => 'Buhay','gender' => 'male','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9620127225','email' => 'ronniel.buhay.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jhanzen','middlename' => 'Rodriguez','lastname' => 'Lopez','gender' => 'male','address' => 'Balitoc, Calatagan Batangas','birthplace' => 'Balitoc, Calatagan Batangas','phone' => '9424744941','email' => 'jhanzen.lopez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'John Alex','middlename' => 'De Jesus','lastname' => 'Binuya','gender' => 'male','address' => '','birthplace' => 'Poblacion 3, Calatagan Batangas','phone' => '9321775829','email' => 'johnalex.binuya.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ma. Vanessa','middlename' => 'Cruz','lastname' => 'Bengcang','gender' => 'female','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9608886575','email' => 'mavanessa.bengcang.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Angelo Kim','middlename' => 'Gonzales','lastname' => 'Espina','gender' => 'male','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9182531732','email' => 'angelokim.espina.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Aila Mei','middlename' => 'Dimaala','lastname' => 'Atienza','gender' => 'female','address' => 'Baragay 7, Nasugbu Batangas','birthplace' => 'Baragay 7, Nasugbu Batangas','phone' => '9354523155','email' => 'ailamei.atienza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Lemuel','middlename' => 'Alvarez','lastname' => 'Capacia','gender' => 'male','address' => 'Butucan Nasugbu Batangas','birthplace' => 'Butucan Nasugbu Batangas','phone' => '9305896417','email' => 'lemuel.capacia.example@g.batstate-u.edu.ph'),
            array('firstname' => 'April Rose','middlename' => 'Feliciano','lastname' => 'Catena','gender' => 'female','address' => 'Pandak na Duhat Nasugbu Batangas','birthplace' => 'Pandak na Duhat Nasugbu Batangas','phone' => '9790362427','email' => 'aprilrose.catena.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jean Dale','middlename' => 'Atienza','lastname' => 'Malabanan','gender' => 'female','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9549487868','email' => 'jeandale.malabanan.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Nel','middlename' => 'Dimaala','lastname' => 'Tolentino','gender' => 'male','address' => 'Barangay 6, Nasugbu Batangas','birthplace' => 'Barangay 6, Nasugbu Batangas','phone' => '9800164856','email' => 'nel.tolentino.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Brandon','middlename' => 'Gonzaga','lastname' => 'Cabatian','gender' => 'male','address' => 'Barangay 4, Nasugbu Batangas','birthplace' => 'Barangay 4, Nasugbu Batangas','phone' => '9280355193','email' => 'brandon.cabatin.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ailyn','middlename' => 'Canzana','lastname' => 'Data','gender' => 'female','address' => 'Bucana Nasugbu Batangas','birthplace' => 'Bucana Nasugbu Batangas','phone' => '9297394528','email' => 'ailyn.data.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Dhenmark','middlename' => 'Taguibao','lastname' => 'Ignaco','gender' => 'male','address' => 'Barangay 8 Nasugbu Batangas','birthplace' => 'Barangay 8 Nasugbu Batangas','phone' => '9496263812','email' => 'dhenmark.ignaco.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Aldwin','middlename' => 'Fraxedes','lastname' => 'Zafra','gender' => 'male','address' => 'Barangay 12 Nasugbu Batangas','birthplace' => 'Barangay 12 Nasugbu Batangas','phone' => '9190363494','email' => 'aldwin.zafra.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Weljun','middlename' => 'Togonon','lastname' => 'De Liola','gender' => 'male','address' => 'Barangay 9 Nasugbu Batangas','birthplace' => 'Barangay 9 Nasugbu Batangas','phone' => '9645814120','email' => 'weljun.deliola.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Noel','middlename' => 'Cuadra','lastname' => 'Carandang','gender' => 'male','address' => 'Barangay 10 Nasugbu Batangas','birthplace' => 'Barangay 10 Nasugbu Batangas','phone' => '9527862684','email' => 'noel.carandang.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Dharwyn','middlename' => 'Tanilon','lastname' => 'Buhay','gender' => 'male','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9482616445','email' => 'dharwyn.buhay.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Edward','middlename' => 'Barangas','lastname' => 'Erna','gender' => 'male','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9341694204','email' => 'edward.erna.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Alexandra Gheil','middlename' => 'Panganiban','lastname' => 'Emaas','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9658353198','email' => 'alexandragheil.emaas.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Rizzalyn','middlename' => 'Lopez','lastname' => 'Ramirez','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9554651818','email' => 'rizzalyn.ramirez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Nicole','middlename' => 'Medrano','lastname' => 'Bascon','gender' => 'female','address' => 'Cumba Lian Batangas','birthplace' => 'Cumba Lian Batangas','phone' => '9298078151','email' => 'nicole.bascon.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Iver','middlename' => 'Conocido','lastname' => 'Mulingbayan','gender' => 'female','address' => 'Puting kahoy Lian Batangas','birthplace' => 'Puting kahoy Lian Batangas','phone' => '9538008340','email' => 'iver.mulingbayan.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Karen','middlename' => 'Lopez','lastname' => 'Bayaborda','gender' => 'female','address' => 'Binubusan Lian Batangas','birthplace' => 'Binubusan Lian Batangas','phone' => '9594855659','email' => 'karen.bayaborda.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Aljhon','middlename' => 'Cruz','lastname' => 'Mulingbayan','gender' => 'male','address' => 'Cumba Lian Batangas','birthplace' => 'Cumba Lian Batangas','phone' => '9936328922','email' => 'aljhon.mulingbayan.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Francis','middlename' => 'Cruz','lastname' => 'Andino','gender' => 'male','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9964743211','email' => 'francis.andino.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jalem','middlename' => 'Gonzales','lastname' => 'Manalastas','gender' => 'male','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9512638231','email' => 'jalem.manalastas.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Salvador','middlename' => 'Dimaala','lastname' => 'Todoc','gender' => 'male','address' => 'Matabungkay Lian Batangas','birthplace' => 'Matabungkay Lian Batangas','phone' => '9648355098','email' => 'salvador.todoc.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Janine','middlename' => 'Alvarez','lastname' => 'Cornejo','gender' => 'female','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9193999039','email' => 'janine.cornejo.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Menalyn','middlename' => 'Feliciano','lastname' => 'Mendoza','gender' => 'female','address' => 'Barangay 6, Nasugbu Batangas','birthplace' => 'Barangay 6, Nasugbu Batangas','phone' => '9162235498','email' => 'menalyn.mendoza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Alfred','middlename' => 'Atienza','lastname' => 'Mendoza','gender' => 'male','address' => 'Barangay 4, Nasugbu Batangas','birthplace' => 'Barangay 4, Nasugbu Batangas','phone' => '9143298010','email' => 'alfred.mendoza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kent Arvin','middlename' => 'Dimaala','lastname' => 'Berbie','gender' => 'male','address' => 'Bucana Nasugbu Batangas','birthplace' => 'Bucana Nasugbu Batangas','phone' => '9323853304','email' => 'kentarvin.berbie.example@g.batstate-u.edu.ph'),
            array('firstname' => 'John Neri','middlename' => 'Gonzaga','lastname' => 'Comeso','gender' => 'male','address' => 'Barangay 8 Nasugbu Batangas','birthplace' => 'Barangay 8 Nasugbu Batangas','phone' => '9171165277','email' => 'johnneri.comeso.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Neil','middlename' => 'Canzana','lastname' => 'Daria','gender' => 'male','address' => 'Barangay 12 Nasugbu Batangas','birthplace' => 'Barangay 12 Nasugbu Batangas','phone' => '9480349952','email' => 'neil.daria.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Marcel','middlename' => 'Taguibao','lastname' => 'Argente','gender' => 'female','address' => 'Barangay 9 Nasugbu Batangas','birthplace' => 'Barangay 9 Nasugbu Batangas','phone' => '9829003187','email' => 'marcel.argente.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Alyssa','middlename' => 'Fraxedes','lastname' => 'Rada','gender' => 'female','address' => 'Barangay 10 Nasugbu Batangas','birthplace' => 'Barangay 10 Nasugbu Batangas','phone' => '9359973461','email' => 'alyssa.rada.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Orlando','middlename' => 'Togonon','lastname' => 'Dilag','gender' => 'male','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9770771524','email' => 'orlando.dilag.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Melissa','middlename' => 'Cuadra','lastname' => 'Erna','gender' => 'female','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9200272693','email' => 'melissa.erna.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Keyzy Rose','middlename' => 'Tanilon','lastname' => 'Dime','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9513803052','email' => 'keyzyrose.dime.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jessa','middlename' => 'Thiel','lastname' => 'Mendoza','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9973881888','email' => 'jessa.mendoza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kimberly','middlename' => 'Kassulke','lastname' => 'Oronico','gender' => 'female','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9488750040','email' => 'kimberly.oronico.example@g.batstate-u.edu.ph'),
            array('firstname' => 'John Kevin','middlename' => 'Conn','lastname' => 'Canha','gender' => 'male','address' => 'PutingKahoy Lian Batangas','birthplace' => 'PutingKahoy Lian Batangas','phone' => '9337301633','email' => 'johnkevin.canha.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kenneth','middlename' => 'Mills','lastname' => 'Varias','gender' => 'male','address' => 'Poblacion 1, Calatagan Batangas','birthplace' => 'Poblacion 1, Calatagan Batangas','phone' => '9871387688','email' => 'kenneth.varias.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Rizza','middlename' => 'Kutch','lastname' => 'Frane','gender' => 'female','address' => 'Poblacion 4, Calatagan Batangas','birthplace' => 'Poblacion 4, Calatagan Batangas','phone' => '9989401532','email' => 'rizza.frane.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jessie','middlename' => 'Denesik','lastname' => 'Andino','gender' => 'female','address' => 'Santa Ana, Calatagan Batangas','birthplace' => 'Santa Ana, Calatagan Batangas','phone' => '9423446965','email' => 'jessie.andino.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Clarissa','middlename' => 'Nienow','lastname' => 'Santos','gender' => 'female','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9993312942','email' => 'clarissa.santos.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ryan','middlename' => 'Crona','lastname' => 'De Guzman','gender' => 'male','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9121758567','email' => 'ryan.deguzman.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Realyn','middlename' => 'Wunsch','lastname' => 'Mercado','gender' => 'female','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9307072383','email' => 'realyn.mercado.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Donnalyn','middlename' => 'Dickinson','lastname' => 'Cirilo','gender' => 'female','address' => 'Pandak na Duhat Nasugbu Batangas','birthplace' => 'Pandak na Duhat Nasugbu Batangas','phone' => '9150614295','email' => 'donnalyn.cirilo.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Michael','middlename' => 'Heller','lastname' => 'Dimaala','gender' => 'male','address' => 'Dayap, Nasugbu Batangas','birthplace' => 'Dayap, Nasugbu Batangas','phone' => '9881975551','email' => 'michael.dimaala.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Judith','middlename' => 'Cruz','lastname' => 'Alvarez','gender' => 'female','address' => 'Biga calatagan batangas','birthplace' => 'Biga calatagan batangas','phone' => '9664554813','email' => 'judithcruz.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Raymart','middlename' => 'Balbar','lastname' => 'Feliciano','gender' => 'male','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9664663218','email' => 'raymartfeliciano.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Casey','middlename' => 'DeCastro','lastname' => 'Atienza','gender' => 'female','address' => 'PutingKahoy Lian Batangas','birthplace' => 'PutingKahoy Lian Batangas','phone' => '9466345187','email' => 'caseyrosedecastro.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Heart','middlename' => 'Faith','lastname' => 'Dimaala','gender' => 'female','address' => 'Poblacion 1, Calatagan Batangas','birthplace' => 'Poblacion 1, Calatagan Batangas','phone' => '9872345678','email' => 'heartfaith.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kim','middlename' => 'Arienza','lastname' => 'Gonzaga','gender' => 'male','address' => 'Poblacion 4, Calatagan Batangas','birthplace' => 'Poblacion 4, Calatagan Batangas','phone' => '9234578123','email' => 'kimatienza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Rose','middlename' => 'Mendoza','lastname' => 'Contis','gender' => 'female','address' => 'Santa Ana, Calatagan Batangas','birthplace' => 'Santa Ana, Calatagan Batangas','phone' => '9874617313','email' => 'rosemendoza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Joseph','middlename' => 'Alvarez','lastname' => 'Santos','gender' => 'male','address' => 'Bagong Silong Calatagan Batangas','birthplace' => 'Bagong Silong Calatagan Batangas','phone' => '9871234572','email' => 'josephalvarez.example@g.batstate-u.edu.ph,'),
            array('firstname' => 'Czarina','middlename' => 'Fontanilla','lastname' => 'Geronimo','gender' => 'female','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9812899647','email' => 'czarinageronimo.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Trixie','middlename' => 'Chua','lastname' => 'Pacia','gender' => 'female','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9123987612','email' => 'trixiepacia.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jolo','middlename' => 'Delos Reyes','lastname' => 'Jonson','gender' => 'male','address' => 'Pandak na Duhat Nasugbu Batangas','birthplace' => 'Pandak na Duhat Nasugbu Batangas','phone' => '9131289837','email' => 'jolojonson.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Miguel','middlename' => 'Mercado','lastname' => 'Capacia','gender' => 'male','address' => 'Dayap, Nasugbu Batangas','birthplace' => 'Dayap, Nasugbu Batangas','phone' => '9832671893','email' => 'miguelmercado.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Joy','middlename' => 'Placio','lastname' => 'Falsado','gender' => 'female','address' => 'Barangay 6, Nasugbu Batangas','birthplace' => 'Barangay 6, Nasugbu Batangas','phone' => '9871256702','email' => 'joyfalsado.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ian','middlename' => 'Gonzales','lastname' => 'Magsino','gender' => 'male','address' => 'Barangay 4 Nasugbu Batangas','birthplace' => 'Barangay 4 Nasugbu Batangas','phone' => '9783215673','email' => 'ianmagsino.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Regin','middlename' => 'Elposar','lastname' => 'Rosales','gender' => 'male','address' => 'Balibago, Calatagan Batangas','birthplace' => 'Balibago, Calatagan Batangas','phone' => '9076512389','email' => 'reginrosales.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Mean','middlename' => 'Macalalad','lastname' => 'Canzana','gender' => 'female','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9987112367','email' => 'meancanzana.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ella','middlename' => 'Macalindong','lastname' => 'Taguibao','gender' => 'female','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9782356718','email' => 'ellataguibao.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Arvin','middlename' => 'Hernandez','lastname' => 'Fraxedes','gender' => 'male','address' => 'Balitoc, Calatagan Batangas','birthplace' => 'Balitoc, Calatagan Batangas','phone' => '9617234719','email' => 'arvinfraxedes.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jairus','middlename' => 'Rodriguez','lastname' => 'Togonon','gender' => 'male','address' => 'Poblacion 3, Calatagan Batangas','birthplace' => 'Poblacion 3, Calatagan Batangas','phone' => '9123786351','email' => 'jairustogonon.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Nica Zandra','middlename' => 'De Jesus','lastname' => 'Cuadra','gender' => 'female','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9173517361','email' => 'nicazandracuadra.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jayson','middlename' => 'Cruz','lastname' => 'Tanilon','gender' => 'male','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9672351739','email' => 'jaysontanilon.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Justin','middlename' => 'Gonzales','lastname' => 'Ignaco','gender' => 'male','address' => 'Baragay 7, Nasugbu Batangas','birthplace' => 'Baragay 7, Nasugbu Batangas','phone' => '9863461892','email' => 'justiignaco.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Roi','middlename' => 'Dimaala','lastname' => 'Faith','gender' => 'male','address' => 'Butucan Nasugbu Batangas','birthplace' => 'Butucan Nasugbu Batangas','phone' => '9210946789','email' => 'roifaith.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Roinel','middlename' => 'Alvarez','lastname' => 'Arienza','gender' => 'male','address' => 'Pandak na Duhat Nasugbu Batangas','birthplace' => 'Pandak na Duhat Nasugbu Batangas','phone' => '9321238909','email' => 'roinnelarienza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Mariel','middlename' => 'Feliciano','lastname' => 'Mendoza','gender' => 'female','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9123489013','email' => 'marielmendoze.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Alicetela','middlename' => 'Atienza','lastname' => 'Alvarez','gender' => 'female','address' => 'Barangay 6, Nasugbu Batangas','birthplace' => 'Barangay 6, Nasugbu Batangas','phone' => '9901234578','email' => 'alicetelaalvarez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Merlita','middlename' => 'Dimaala','lastname' => 'Fontanilla','gender' => 'female','address' => 'Barangay 4, Nasugbu Batangas','birthplace' => 'Barangay 4, Nasugbu Batangas','phone' => '9123890123','email' => 'merlitafontanilla.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Angela','middlename' => 'Gonzaga','lastname' => 'Chua','gender' => 'female','address' => 'Bucana Nasugbu Batangas','birthplace' => 'Bucana Nasugbu Batangas','phone' => '9872319023','email' => 'angelachua.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Angel','middlename' => 'Canzana','lastname' => 'Cruz','gender' => 'female','address' => 'Barangay 8 Nasugbu Batangas','birthplace' => 'Barangay 8 Nasugbu Batangas','phone' => '9123789457','email' => 'angelcruz.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Abigail','middlename' => 'Taguibao','lastname' => 'Atienza','gender' => 'female','address' => 'Barangay 12 Nasugbu Batangas','birthplace' => 'Barangay 12 Nasugbu Batangas','phone' => '9123478956','email' => 'abigailatienza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Cruella','middlename' => 'Fraxedes','lastname' => 'Arienza','gender' => 'female','address' => 'Barangay 9 Nasugbu Batangas','birthplace' => 'Barangay 9 Nasugbu Batangas','phone' => '9123489234','email' => 'cruellaatienza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Stella','middlename' => 'Togonon','lastname' => 'Dalida','gender' => 'female','address' => 'Barangay 10 Nasugbu Batangas','birthplace' => 'Barangay 10 Nasugbu Batangas','phone' => '9781236519','email' => 'stelladalida.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Baroness','middlename' => 'Cuadra','lastname' => 'Gal','gender' => 'male','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9123489023','email' => 'baronessgal.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Gigi','middlename' => 'Tanilon','lastname' => 'Gonzaga','gender' => 'female','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9137826790','email' => 'gigigonzaga.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Anna','middlename' => 'Barangas','lastname' => 'Villarin','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9123789713','email' => 'annavillarin.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Perlyn','middlename' => 'Panganiban','lastname' => 'Bonsol','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9876345678','email' => 'perlynbonsol.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Patrick','middlename' => 'Lopez','lastname' => 'Deguzman','gender' => 'male','address' => 'Cumba Lian Batangas','birthplace' => 'Cumba Lian Batangas','phone' => '9371452146','email' => 'patrickdeguzman.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kyle','middlename' => 'Medrano','lastname' => 'Rodriguez','gender' => 'male','address' => 'Puting kahoy Lian Batangas','birthplace' => 'Puting kahoy Lian Batangas','phone' => '9286414244','email' => 'kylerodriguez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jayson','middlename' => 'Conocido','lastname' => 'Banaguas','gender' => 'male','address' => 'Binubusan Lian Batangas','birthplace' => 'Binubusan Lian Batangas','phone' => '9826374712','email' => 'jaysonbanaguas.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Lanie','middlename' => 'Lopez','lastname' => 'Panganiban','gender' => 'female','address' => 'Cumba Lian Batangas','birthplace' => 'Cumba Lian Batangas','phone' => '9764523547','email' => 'laniepanganiban.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Arnold','middlename' => 'Cruz','lastname' => 'Roxas','gender' => 'male','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9435313234','email' => 'arnoldroxas.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Ivan','middlename' => 'Borja','lastname' => 'Atienza','gender' => 'male','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9673545685','email' => 'ivanatienza.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Mary Rose','middlename' => 'Daigdigan','lastname' => 'Dalida','gender' => 'female','address' => 'Matabungkay Lian Batangas','birthplace' => 'Matabungkay Lian Batangas','phone' => '9432157464','email' => 'maryrosedalida.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Lester','middlename' => 'Demesa','lastname' => 'Walog','gender' => 'male','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9823421789','email' => 'lesterwalog.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Jonel','middlename' => 'Bacit','lastname' => 'Salvador','gender' => 'male','address' => 'Barangay 6, Nasugbu Batangas','birthplace' => 'Barangay 6, Nasugbu Batangas','phone' => '9128967345','email' => 'jonelsalvador.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Alexandra Gheil','middlename' => 'Basco','lastname' => 'Ogaya','gender' => 'female','address' => 'Barangay 4, Nasugbu Batangas','birthplace' => 'Barangay 4, Nasugbu Batangas','phone' => '9871627834','email' => 'alexandraogaya.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Anji','middlename' => 'Abiad','lastname' => 'Lopez','gender' => 'female','address' => 'Bucana Nasugbu Batangas','birthplace' => 'Bucana Nasugbu Batangas','phone' => '9132689234','email' => 'anjilopez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'KD','middlename' => 'Manalo','lastname' => 'Barangas','gender' => 'male','address' => 'Barangay 8 Nasugbu Batangas','birthplace' => 'Barangay 8 Nasugbu Batangas','phone' => '9138976421','email' => 'kdbarangas.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Vicky','middlename' => 'Cruz','lastname' => 'Panganiban','gender' => 'female','address' => 'Barangay 12 Nasugbu Batangas','birthplace' => 'Barangay 12 Nasugbu Batangas','phone' => '9476334590','email' => 'vickypanganiban.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Billie','middlename' => 'Chua','lastname' => 'Lopez','gender' => 'female','address' => 'Barangay 9 Nasugbu Batangas','birthplace' => 'Barangay 9 Nasugbu Batangas','phone' => '9123784567','email' => 'billielopez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Allan','middlename' => 'Canzana','lastname' => 'Medrano','gender' => 'male','address' => 'Barangay 10 Nasugbu Batangas','birthplace' => 'Barangay 10 Nasugbu Batangas','phone' => '9238967189','email' => 'allanmedrano.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Grace','middlename' => 'Baon','lastname' => 'Conocido','gender' => 'female','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9123789234','email' => 'graceconocido.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kaye','middlename' => 'Fausto','lastname' => 'Gonzales','gender' => 'female','address' => 'Wawa, Nasugbu Batangas','birthplace' => 'Wawa, Nasugbu Batangas','phone' => '9128934569','email' => 'kayegonzales.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Aicell','middlename' => 'Gongon','lastname' => 'Elposar','gender' => 'female','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9234677899','email' => 'aicellelposar.example@g.batstate-u.edu.ph'),
            array('firstname' => 'David','middlename' => 'Benson','lastname' => 'Macalalad','gender' => 'male','address' => 'Bulihan Nasugbu Batangas','birthplace' => 'Bulihan Nasugbu Batangas','phone' => '9922337812','email' => 'davidmacalalad.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kristine','middlename' => 'Gaffud','lastname' => 'Macalindong','gender' => 'female','address' => 'Prenza Lian Batangas','birthplace' => 'Prenza Lian Batangas','phone' => '9123372226','email' => 'kristinemacalindong.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Zach','middlename' => 'Escota','lastname' => 'Hernandez','gender' => 'male','address' => 'PutingKahoy Lian Batangas','birthplace' => 'PutingKahoy Lian Batangas','phone' => '9672389123','email' => 'zachhernandez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Nicko','middlename' => 'Espina','lastname' => 'Rodriguez','gender' => 'male','address' => 'Poblacion 1, Calatagan Batangas','birthplace' => 'Poblacion 1, Calatagan Batangas','phone' => '9238913454','email' => 'nickorodrodriguez.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Raymond','middlename' => 'Tesoro','lastname' => 'Custudio','gender' => 'male','address' => 'Poblacion 4, Calatagan Batangas','birthplace' => 'Poblacion 4, Calatagan Batangas','phone' => '9975537980','email' => 'raymondcustodio.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Randy','middlename' => 'Mercado','lastname' => 'Reyes','gender' => 'male','address' => 'Santa Ana, Calatagan Batangas','birthplace' => 'Santa Ana, Calatagan Batangas','phone' => '9367899903','email' => 'randymercado.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Edgar','middlename' => 'Placio','lastname' => 'Padilla','gender' => 'male','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9878903456','email' => 'edgarpadilla.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Rommel','middlename' => 'Arellano','lastname' => 'Daffun','gender' => 'male','address' => 'Barangay 1, Nasugbu Batangas','birthplace' => 'Barangay 1, Nasugbu Batangas','phone' => '9812350987','email' => 'rommeldaffun.example@g.batstate-u.edu.ph'),
            array('firstname' => 'MJ','middlename' => 'Panganiban','lastname' => 'Escarilla','gender' => 'male','address' => 'Barangay 5 Nasugbu Batangas','birthplace' => 'Barangay 5 Nasugbu Batangas','phone' => '9808923123','email' => 'mjescarilla.example@g.batstate-u.edu.ph'),
            array('firstname' => 'TJ','middlename' => 'Villarin','lastname' => 'Togonon','gender' => 'male','address' => 'Pandak na Duhat Nasugbu Batangas','birthplace' => 'Pandak na Duhat Nasugbu Batangas','phone' => '9182345678','email' => 'tjtogonon.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Christian','middlename' => 'Villeza','lastname' => 'Vivas','gender' => 'male','address' => 'Dayap, Nasugbu Batangas','birthplace' => 'Dayap, Nasugbu Batangas','phone' => '9023451789','email' => 'christianvivas.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Leeyan','middlename' => 'Zapata','lastname' => 'Par','gender' => 'male','address' => 'Barangay 6, Nasugbu Batangas','birthplace' => 'Barangay 6, Nasugbu Batangas','phone' => '9223789123','email' => 'leeyanpar.example@g.batstate-u.edu.ph'),
            array('firstname' => 'Kristoff','middlename' => 'Macalalad','lastname' => 'Limueco','gender' => 'male','address' => 'Barangay 4 Nasugbu Batangas','birthplace' => 'Barangay 4 Nasugbu Batangas','phone' => '9123789134','email' => 'kristofflimueco.example@g.batstate-u.edu.ph'),
            array('firstname' => 'JK','middlename' => 'Macalindong','lastname' => 'Limoico','gender' => 'male','address' => 'Balibago, Calatagan Batangas','birthplace' => 'Balibago, Calatagan Batangas','phone' => '9123178903','email' => 'jklimoico.example@g.batstate-u.edu.ph')
          );

        foreach ($scholars as $key => $scholar) {
            User::factory()->create([
                'firstname' => $scholar['firstname'],
                'middlename' => $scholar['middlename'],
                'lastname' => $scholar['lastname'],
                'gender' => $scholar['gender'],
                'address' => $scholar['address'],
                'birthplace' => $scholar['birthplace'],
                'phone' => '0'.$scholar['phone'],
                'email' => $scholar['email'],
            ]);
        }
    }
}
