<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::insert([
            [   
                'usertype'      => 'admin',
                'firstname'     => 'Rhannel',
                'middlename'    => 'Dalida',
                'lastname'      => 'Dinlasan',
                'gender'        => 'male',
                'religion'      => 'Roman Catholic',
                'birthday'      => '1999-12-07',
                'birthplace'    => 'Biga, Calatagan, Batangas',
                'address'       => 'Biga, Calatagan, Batangas',
                'phone'         => '09351458776',
                'email'         => 'rhannel.dinlasan@g.batstate-u.edu.ph',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'officer',
                'firstname'     => 'Hazel',
                'middlename'    => 'Gal',
                'lastname'      => 'Gonzales',
                'gender'        => 'female',
                'religion'      => 'Roman Catholic',
                'birthday'      => '1999-10-23',
                'birthplace'    => 'Tanagan, Calatagan, Batangas',
                'address'       => 'Tanagan, Calatagan, Batangas',
                'phone'         => '09664554812',
                'email'         => 'hazel.gonzales@g.batstate-u.edu.ph',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [   
                'usertype'      => 'scholar',
                'firstname'     => 'John Raven',
                'middlename'    => 'Rodriguez',
                'lastname'      => 'Balbar',
                'gender'        => 'male',
                'religion'      => 'Roman Catholic',
                'birthday'      => '2000-09-17',
                'birthplace'    => 'Cumba, Lian , Batangas',
                'address'       => 'Cumba, Lian , Batangas',
                'phone'         => '09664250790',
                'email'         => 'johnraven.balbar@g.batstate-u.edu.ph',
                'password'      => Hash::make('123123123'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
        ]);

        $scholars = array(
            array('firstname' => 'Ren','middlename' => 'Eroles','lastname' => 'Dalida','email' => 'rendalida@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-09-03','address' => 'Biga, Calatagan, Batangas'),
            array('firstname' => 'Alzeo','middlename' => 'Togonon','lastname' => 'Landicho','email' => 'alzeo.landicho.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-17','address' => 'Matabungkay Lian Batangas'),
            array('firstname' => 'Alvin','middlename' => 'Dimaala','lastname' => 'Dalida','email' => 'alvin.dalida.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-06-23','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Analy','middlename' => 'Cuadra','lastname' => 'Dalida','email' => 'analy.dalida.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-01-15','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Jaypee','middlename' => 'Conocido','lastname' => 'Venzon','email' => 'jaypee.venzon.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-07-13','address' => 'Puting kahoy Lian Batangas'),
            array('firstname' => 'Daisy','middlename' => 'Barangas','lastname' => 'Elposar','email' => 'daisy.elposar.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-08-31','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Nikki Sofia','middlename' => 'Lopez','lastname' => 'Mailig','email' => 'nikkisofia.mailig.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-04-22','address' => 'Baragay 7, Nasugbu Batangas'),
            array('firstname' => 'Ryan','middlename' => 'Tanilon','lastname' => 'De Luna','email' => 'ryan.deluna.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-01-10','address' => 'Baragay 7, Nasugbu Batangas'),
            array('firstname' => 'Jayrald','middlename' => 'Dimaala','lastname' => 'Holgado','email' => 'jayrald.holgado.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-06-18','address' => 'Poblacion 3, Calatagan Batangas'),
            array('firstname' => 'Ian Glenn','middlename' => 'Togonon','lastname' => 'Mercado','email' => 'ianglenn.mercado.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-06-02','address' => 'Barangay 4 Nasugbu Batangas'),
            array('firstname' => 'Judith','middlename' => 'Macalalad','lastname' => 'Manalo','email' => 'judith.manalo.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-12-18','address' => 'Balibago, Calatagan Batangas'),
            array('firstname' => 'John Paul','middlename' => 'Macalindong','lastname' => 'Macalindong','email' => 'johnpaul.macalindong.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-11-16','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Ronniel','middlename' => 'Hernandez','lastname' => 'Buhay','email' => 'ronniel.buhay.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-05-06','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Jhanzen','middlename' => 'Rodriguez','lastname' => 'Lopez','email' => 'jhanzen.lopez.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-09-16','address' => 'Balitoc, Calatagan Batangas'),
            array('firstname' => 'John Alex','middlename' => 'De Jesus','lastname' => 'Binuya','email' => 'johnalex.binuya.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-09-17','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Ma. Vanessa','middlename' => 'Cruz','lastname' => 'Bengcang','email' => 'mavanessa.bengcang.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-29','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Angelo Kim','middlename' => 'Gonzales','lastname' => 'Espina','email' => 'angelokim.espina.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-10-10','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Aila Mei','middlename' => 'Dimaala','lastname' => 'Atienza','email' => 'ailamei.atienza.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-11-12','address' => 'Baragay 7, Nasugbu Batangas'),
            array('firstname' => 'Lemuel','middlename' => 'Alvarez','lastname' => 'Capacia','email' => 'lemuel.capacia.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-02-27','address' => 'Butucan Nasugbu Batangas'),
            array('firstname' => 'April Rose','middlename' => 'Feliciano','lastname' => 'Catena','email' => 'aprilrose.catena.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-25','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Jean Dale','middlename' => 'Atienza','lastname' => 'Malabanan','email' => 'jeandale.malabanan.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-05-11','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Nel','middlename' => 'Dimaala','lastname' => 'Tolentino','email' => 'nel.tolentino.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-01-03','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Brandon','middlename' => 'Gonzaga','lastname' => 'Cabatian','email' => 'brandon.cabatin.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-06-19','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Ailyn','middlename' => 'Canzana','lastname' => 'Data','email' => 'ailyn.data.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-12-23','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Dhenmark','middlename' => 'Taguibao','lastname' => 'Ignaco','email' => 'dhenmark.ignaco.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-12-04','address' => 'Barangay 8 Nasugbu Batangas'),
            array('firstname' => 'Aldwin','middlename' => 'Fraxedes','lastname' => 'Zafra','email' => 'aldwin.zafra.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-04-18','address' => 'Barangay 12 Nasugbu Batangas'),
            array('firstname' => 'Weljun','middlename' => 'Togonon','lastname' => 'De Liola','email' => 'weljun.deliola.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-03-23','address' => 'Barangay 9 Nasugbu Batangas'),
            array('firstname' => 'Noel','middlename' => 'Cuadra','lastname' => 'Carandang','email' => 'noel.carandang.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-03-02','address' => 'Barangay 10 Nasugbu Batangas'),
            array('firstname' => 'Dharwyn','middlename' => 'Tanilon','lastname' => 'Buhay','email' => 'dharwyn.buhay.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-09-09','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Edward','middlename' => 'Barangas','lastname' => 'Erna','email' => 'edward.erna.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-03-10','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Alexandra Gheil','middlename' => 'Panganiban','lastname' => 'Emaas','email' => 'alexandragheil.emaas.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-07-25','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Rizzalyn','middlename' => 'Lopez','lastname' => 'Ramirez','email' => 'rizzalyn.ramirez.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-27','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Nicole','middlename' => 'Medrano','lastname' => 'Bascon','email' => 'nicole.bascon.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-06-04','address' => 'Cumba Lian Batangas'),
            array('firstname' => 'Iver','middlename' => 'Conocido','lastname' => 'Mulingbayan','email' => 'iver.mulingbayan.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-11-04','address' => 'Puting kahoy Lian Batangas'),
            array('firstname' => 'Karen','middlename' => 'Lopez','lastname' => 'Bayaborda','email' => 'karen.bayaborda.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-06-23','address' => 'Binubusan Lian Batangas'),
            array('firstname' => 'Aljhon','middlename' => 'Cruz','lastname' => 'Mulingbayan','email' => 'aljhon.mulingbayan.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-12-13','address' => 'Cumba Lian Batangas'),
            array('firstname' => 'Francis','middlename' => 'Cruz','lastname' => 'Andino','email' => 'francis.andino.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-10-04','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Jalem','middlename' => 'Gonzales','lastname' => 'Manalastas','email' => 'jalem.manalastas.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-06-08','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Salvador','middlename' => 'Dimaala','lastname' => 'Todoc','email' => 'salvador.todoc.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-10-12','address' => 'Matabungkay Lian Batangas'),
            array('firstname' => 'Janine','middlename' => 'Alvarez','lastname' => 'Cornejo','email' => 'janine.cornejo.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-02-13','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Menalyn','middlename' => 'Feliciano','lastname' => 'Mendoza','email' => 'menalyn.mendoza.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-06-24','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Alfred','middlename' => 'Atienza','lastname' => 'Mendoza','email' => 'alfred.mendoza.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-08-28','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Kent Arvin','middlename' => 'Dimaala','lastname' => 'Berbie','email' => 'kentarvin.berbie.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-05','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'John Neri','middlename' => 'Gonzaga','lastname' => 'Comeso','email' => 'johnneri.comeso.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-03-05','address' => 'Barangay 8 Nasugbu Batangas'),
            array('firstname' => 'Neil','middlename' => 'Canzana','lastname' => 'Daria','email' => 'neil.daria.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-05-06','address' => 'Barangay 12 Nasugbu Batangas'),
            array('firstname' => 'Marcel','middlename' => 'Taguibao','lastname' => 'Argente','email' => 'marcel.argente.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-10-28','address' => 'Barangay 9 Nasugbu Batangas'),
            array('firstname' => 'Alyssa','middlename' => 'Fraxedes','lastname' => 'Rada','email' => 'alyssa.rada.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-01-10','address' => 'Barangay 10 Nasugbu Batangas'),
            array('firstname' => 'Orlando','middlename' => 'Togonon','lastname' => 'Dilag','email' => 'orlando.dilag.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-02-02','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Melissa','middlename' => 'Cuadra','lastname' => 'Erna','email' => 'melissa.erna.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-18','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Keyzy Rose','middlename' => 'Tanilon','lastname' => 'Dime','email' => 'keyzyrose.dime.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-06-21','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Jessa','middlename' => 'Thiel','lastname' => 'Mendoza','email' => 'jessa.mendoza.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-02-17','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Kimberly','middlename' => 'Kassulke','lastname' => 'Oronico','email' => 'kimberly.oronico.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-06-30','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'John Kevin','middlename' => 'Conn','lastname' => 'Canha','email' => 'johnkevin.canha.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-11-20','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Kenneth','middlename' => 'Mills','lastname' => 'Varias','email' => 'kenneth.varias.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-09-19','address' => 'Poblacion 1, Calatagan Batangas'),
            array('firstname' => 'Rizza','middlename' => 'Kutch','lastname' => 'Frane','email' => 'rizza.frane.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-02-01','address' => 'Poblacion 4, Calatagan Batangas'),
            array('firstname' => 'Jessie','middlename' => 'Denesik','lastname' => 'Andino','email' => 'jessie.andino.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-11-23','address' => 'Santa Ana, Calatagan Batangas'),
            array('firstname' => 'Clarissa','middlename' => 'Nienow','lastname' => 'Santos','email' => 'clarissa.santos.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-05-08','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Ryan','middlename' => 'Crona','lastname' => 'De Guzman','email' => 'ryan.deguzman.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-07-17','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Realyn','middlename' => 'Wunsch','lastname' => 'Mercado','email' => 'realyn.mercado.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-09-15','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Donnalyn','middlename' => 'Dickinson','lastname' => 'Cirilo','email' => 'donnalyn.cirilo.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-02-01','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Michael','middlename' => 'Heller','lastname' => 'Dimaala','email' => 'michael.dimaala.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-01','address' => 'Dayap, Nasugbu Batangas'),
            array('firstname' => 'Judith','middlename' => 'Cruz','lastname' => 'Alvarez','email' => 'judithcruz.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-01','address' => 'Biga calatagan batangas'),
            array('firstname' => 'Raymart','middlename' => 'Balbar','lastname' => 'Feliciano','email' => 'raymartfeliciano.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-11-27','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Casey','middlename' => 'DeCastro','lastname' => 'Atienza','email' => 'caseyrosedecastro.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-02-04','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Heart','middlename' => 'Faith','lastname' => 'Dimaala','email' => 'heartfaith.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-06-30','address' => 'Poblacion 1, Calatagan Batangas'),
            array('firstname' => 'Kim','middlename' => 'Arienza','lastname' => 'Gonzaga','email' => 'kimatienza.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-12-13','address' => 'Poblacion 4, Calatagan Batangas'),
            array('firstname' => 'Rose','middlename' => 'Mendoza','lastname' => 'Contis','email' => 'rosemendoza.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-12-24','address' => 'Santa Ana, Calatagan Batangas'),
            array('firstname' => 'Joseph','middlename' => 'Alvarez','lastname' => 'Santos','email' => 'josephalvarez.example@g.batstate-u.edu.ph,','gender' => 'male','birthday' => '2000-01-02','address' => 'Bagong Silong Calatagan Batangas'),
            array('firstname' => 'Czarina','middlename' => 'Fontanilla','lastname' => 'Geronimo','email' => 'czarinageronimo.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-09-10','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Trixie','middlename' => 'Chua','lastname' => 'Pacia','email' => 'trixiepacia.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-01-21','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Jolo','middlename' => 'Delos Reyes','lastname' => 'Jonson','email' => 'jolojonson.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-22','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Miguel','middlename' => 'Mercado','lastname' => 'Capacia','email' => 'miguelmercado.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-11-27','address' => 'Dayap, Nasugbu Batangas'),
            array('firstname' => 'Joy','middlename' => 'Placio','lastname' => 'Falsado','email' => 'joyfalsado.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-11-16','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Ian','middlename' => 'Gonzales','lastname' => 'Magsino','email' => 'ianmagsino.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-03-24','address' => 'Barangay 4 Nasugbu Batangas'),
            array('firstname' => 'Regin','middlename' => 'Elposar','lastname' => 'Rosales','email' => 'reginrosales.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-12-13','address' => 'Balibago, Calatagan Batangas'),
            array('firstname' => 'Mean','middlename' => 'Macalalad','lastname' => 'Canzana','email' => 'meancanzana.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-13','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Ella','middlename' => 'Macalindong','lastname' => 'Taguibao','email' => 'ellataguibao.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-07-15','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Arvin','middlename' => 'Hernandez','lastname' => 'Fraxedes','email' => 'arvinfraxedes.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-08-02','address' => 'Balitoc, Calatagan Batangas'),
            array('firstname' => 'Jairus','middlename' => 'Rodriguez','lastname' => 'Togonon','email' => 'jairustogonon.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-06-24','address' => 'Poblacion 3, Calatagan Batangas'),
            array('firstname' => 'Nica Zandra','middlename' => 'De Jesus','lastname' => 'Cuadra','email' => 'nicazandracuadra.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-04-24','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Jayson','middlename' => 'Cruz','lastname' => 'Tanilon','email' => 'jaysontanilon.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-04-18','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Justin','middlename' => 'Gonzales','lastname' => 'Ignaco','email' => 'justiignaco.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-03-19','address' => 'Baragay 7, Nasugbu Batangas'),
            array('firstname' => 'Roi','middlename' => 'Dimaala','lastname' => 'Faith','email' => 'roifaith.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-02-28','address' => 'Butucan Nasugbu Batangas'),
            array('firstname' => 'Roinel','middlename' => 'Alvarez','lastname' => 'Arienza','email' => 'roinnelarienza.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-01-23','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Mariel','middlename' => 'Feliciano','lastname' => 'Mendoza','email' => 'marielmendoze.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-02-21','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Alicetela','middlename' => 'Atienza','lastname' => 'Alvarez','email' => 'alicetelaalvarez.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-06-07','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Merlita','middlename' => 'Dimaala','lastname' => 'Fontanilla','email' => 'merlitafontanilla.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-02-14','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Angela','middlename' => 'Gonzaga','lastname' => 'Chua','email' => 'angelachua.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-04-21','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Angel','middlename' => 'Canzana','lastname' => 'Cruz','email' => 'angelcruz.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-11-13','address' => 'Barangay 8 Nasugbu Batangas'),
            array('firstname' => 'Abigail','middlename' => 'Taguibao','lastname' => 'Atienza','email' => 'abigailatienza.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-05-17','address' => 'Barangay 12 Nasugbu Batangas'),
            array('firstname' => 'Cruella','middlename' => 'Fraxedes','lastname' => 'Arienza','email' => 'cruellaatienza.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-12-27','address' => 'Barangay 9 Nasugbu Batangas'),
            array('firstname' => 'Stella','middlename' => 'Togonon','lastname' => 'Dalida','email' => 'stelladalida.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-12-27','address' => 'Barangay 10 Nasugbu Batangas'),
            array('firstname' => 'Baroness','middlename' => 'Cuadra','lastname' => 'Gal','email' => 'baronessgal.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-01','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Gigi','middlename' => 'Tanilon','lastname' => 'Gonzaga','email' => 'gigigonzaga.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-11-16','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Anna','middlename' => 'Barangas','lastname' => 'Villarin','email' => 'annavillarin.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-03-02','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Perlyn','middlename' => 'Panganiban','lastname' => 'Bonsol','email' => 'perlynbonsol.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-04-15','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Patrick','middlename' => 'Lopez','lastname' => 'Deguzman','email' => 'patrickdeguzman.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-02-11','address' => 'Cumba Lian Batangas'),
            array('firstname' => 'Kyle','middlename' => 'Medrano','lastname' => 'Rodriguez','email' => 'kylerodriguez.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-11-20','address' => 'Puting kahoy Lian Batangas'),
            array('firstname' => 'Jayson','middlename' => 'Conocido','lastname' => 'Banaguas','email' => 'jaysonbanaguas.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-10-13','address' => 'Binubusan Lian Batangas'),
            array('firstname' => 'Lanie','middlename' => 'Lopez','lastname' => 'Panganiban','email' => 'laniepanganiban.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-04-20','address' => 'Cumba Lian Batangas'),
            array('firstname' => 'Arnold','middlename' => 'Cruz','lastname' => 'Roxas','email' => 'arnoldroxas.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-11-06','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Ivan','middlename' => 'Borja','lastname' => 'Atienza','email' => 'ivanatienza.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-08-23','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Mary Rose','middlename' => 'Daigdigan','lastname' => 'Dalida','email' => 'maryrosedalida.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-08-25','address' => 'Matabungkay Lian Batangas'),
            array('firstname' => 'Lester','middlename' => 'Demesa','lastname' => 'Walog','email' => 'lesterwalog.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-04-02','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Jonel','middlename' => 'Bacit','lastname' => 'Salvador','email' => 'jonelsalvador.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-01-02','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Alexandra Gheil','middlename' => 'Basco','lastname' => 'Ogaya','email' => 'alexandraogaya.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-04-22','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Anji','middlename' => 'Abiad','lastname' => 'Lopez','email' => 'anjilopez.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-03-14','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'KD','middlename' => 'Manalo','lastname' => 'Barangas','email' => 'kdbarangas.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-02-11','address' => 'Barangay 8 Nasugbu Batangas'),
            array('firstname' => 'Vicky','middlename' => 'Cruz','lastname' => 'Panganiban','email' => 'vickypanganiban.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-10-12','address' => 'Barangay 12 Nasugbu Batangas'),
            array('firstname' => 'Billie','middlename' => 'Chua','lastname' => 'Lopez','email' => 'billielopez.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-01-29','address' => 'Barangay 9 Nasugbu Batangas'),
            array('firstname' => 'Allan','middlename' => 'Canzana','lastname' => 'Medrano','email' => 'allanmedrano.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-08-18','address' => 'Barangay 10 Nasugbu Batangas'),
            array('firstname' => 'Grace','middlename' => 'Baon','lastname' => 'Conocido','email' => 'graceconocido.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-07-20','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Kaye','middlename' => 'Fausto','lastname' => 'Gonzales','email' => 'kayegonzales.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-04-20','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Aicell','middlename' => 'Gongon','lastname' => 'Elposar','email' => 'aicellelposar.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-06-22','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'David','middlename' => 'Benson','lastname' => 'Macalalad','email' => 'davidmacalalad.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-06-11','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Kristine','middlename' => 'Gaffud','lastname' => 'Macalindong','email' => 'kristinemacalindong.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-01-24','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Zach','middlename' => 'Escota','lastname' => 'Hernandez','email' => 'zachhernandez.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-07-14','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Nicko','middlename' => 'Espina','lastname' => 'Rodriguez','email' => 'nickorodrodriguez.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-05-11','address' => 'Poblacion 1, Calatagan Batangas'),
            array('firstname' => 'Raymond','middlename' => 'Tesoro','lastname' => 'Custudio','email' => 'raymondcustodio.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-04-26','address' => 'Poblacion 4, Calatagan Batangas'),
            array('firstname' => 'Randy','middlename' => 'Mercado','lastname' => 'Reyes','email' => 'randymercado.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-08-21','address' => 'Santa Ana, Calatagan Batangas'),
            array('firstname' => 'Edgar','middlename' => 'Placio','lastname' => 'Padilla','email' => 'edgarpadilla.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-29','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Rommel','middlename' => 'Arellano','lastname' => 'Daffun','email' => 'rommeldaffun.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-07-17','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'MJ','middlename' => 'Panganiban','lastname' => 'Escarilla','email' => 'mjescarilla.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-04-04','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'TJ','middlename' => 'Villarin','lastname' => 'Togonon','email' => 'tjtogonon.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-08-22','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Christian','middlename' => 'Villeza','lastname' => 'Vivas','email' => 'christianvivas.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-17','address' => 'Dayap, Nasugbu Batangas'),
            array('firstname' => 'Leeyan','middlename' => 'Zapata','lastname' => 'Par','email' => 'leeyanpar.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-05-31','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Kristoff','middlename' => 'Macalalad','lastname' => 'Limueco','email' => 'kristofflimueco.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-04-05','address' => 'Barangay 4 Nasugbu Batangas'),
            array('firstname' => 'JK','middlename' => 'Macalindong','lastname' => 'Limjoco','email' => 'jklimoico.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-01-25','address' => 'Balibago, Calatagan Batangas'),
            array('firstname' => 'Kier','middlename' => 'Dela Cruz','lastname' => 'Peralta','email' => 'kier.peralta.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-01-09','address' => 'Poblacion 4, Calatagan Batangas'),
            array('firstname' => 'Maria','middlename' => 'Garcia','lastname' => 'Vargas','email' => 'maria.vargas.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-12-27','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Christine','middlename' => 'Reyes','lastname' => 'Cabrera','email' => 'christine .cabrera.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-06-10','address' => 'Poblacion 3, Calatagan Batangas'),
            array('firstname' => 'Hannah','middlename' => 'Ramos','lastname' => 'Fajardo','email' => 'hannah.fajardo.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-12-27','address' => 'Matabungkay Lian Batangas'),
            array('firstname' => 'Kate','middlename' => 'Mendoza','lastname' => 'Gonzaga','email' => 'kate.gonzaga.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-01-06','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Grace','middlename' => 'Santos','lastname' => 'Espina','email' => 'grace.espina.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-04-05','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Jane','middlename' => 'Flores','lastname' => 'Guevarra','email' => 'jane.guevarra.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-12-06','address' => 'Puting kahoy Lian Batangas'),
            array('firstname' => 'Angela','middlename' => 'Gonzales','lastname' => 'Samson','email' => 'angela.samson.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-01-08','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Danielle','middlename' => 'Baustista','lastname' => 'Ortega','email' => 'danielle.ortega.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-01-17','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Nicole','middlename' => 'Villanueva','lastname' => 'Molina','email' => 'nicole.molina.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-11-22','address' => 'Puting kahoy Lian Batangas'),
            array('firstname' => 'Bianca','middlename' => 'Fernandez','lastname' => 'Serrano','email' => 'bianca.serrano.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-01-28','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Valerie','middlename' => 'Cruz','lastname' => 'Chavez','email' => 'valerie.chavez.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-03-18','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Alexa','middlename' => 'De guzman','lastname' => 'Brioness','email' => 'alexa.brioness.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-01-21','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Claire','middlename' => 'Lopez','lastname' => 'Medina','email' => 'claire.medina.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-08-01','address' => 'Cumba Lian Batangas'),
            array('firstname' => 'Angelo','middlename' => 'Perez','lastname' => 'Palma','email' => 'angelo.palma.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-12-29','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Grant','middlename' => 'Callio','lastname' => 'Tamayo','email' => 'grant.tamayo.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-07-26','address' => 'Balibago, Calatagan Batangas'),
            array('firstname' => 'Tristan','middlename' => 'Francisco','lastname' => 'Arellano','email' => 'tristan.arellano.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-10-06','address' => 'Poblacion 1, Calatagan Batangas'),
            array('firstname' => 'Kurt','middlename' => 'Rivera','lastname' => 'Atienza','email' => 'kurt.atienza.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-03-02','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Kim','middlename' => 'Aquino','lastname' => 'Estrade','email' => 'kim.estrade.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-01-30','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Ana','middlename' => 'Castro','lastname' => 'Martin','email' => 'ana.martin.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-11-23','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Karen','middlename' => 'Sanchez','lastname' => 'Acousta','email' => 'karen.acousta.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-09-30','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Steffanie','middlename' => 'Torres','lastname' => 'Dizon','email' => 'steffanie.dizon.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-04-23','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Sofia','middlename' => 'De leon','lastname' => 'Sison','email' => 'sofia.sison.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-01-04','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Joy','middlename' => 'Domingo','lastname' => 'Trinidad','email' => 'joy.trinidad.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-12-19','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'May','middlename' => 'Martinez','lastname' => 'Samora','email' => 'may.samora.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-01-06','address' => 'Barangay 12 Nasugbu Batangas'),
            array('firstname' => 'Lorraine','middlename' => 'Rodriguez','lastname' => 'Asuncion','email' => 'lorraine.asuncion.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-07-09','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Ted','middlename' => 'Santiago','lastname' => 'Abad','email' => 'ted.abad.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-05-03','address' => 'Matabungkay Lian Batangas'),
            array('firstname' => 'Eddy','middlename' => 'Soriano','lastname' => 'Moreno','email' => 'eddy.moreno.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-01-30','address' => 'Barangay 4 Nasugbu Batangas'),
            array('firstname' => 'Carl','middlename' => 'Delos Santos','lastname' => 'Cabalero','email' => 'carl.cabalero.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-06-29','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Sandy','middlename' => 'Diaz','lastname' => 'Villamor','email' => 'sandy.villamor.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-08-08','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Rose','middlename' => 'Hernandez','lastname' => 'Berndardo','email' => 'rose.berndardo.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-05-23','address' => 'Santa Ana, Calatagan Batangas'),
            array('firstname' => 'Frances','middlename' => 'Tolentino','lastname' => 'Robles','email' => 'frances.robles.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-03-21','address' => 'Tanagan, Calatagan, Batangas'),
            array('firstname' => 'Michelle','middlename' => 'Valdez','lastname' => 'Conception','email' => 'michelle.conception.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-05-18','address' => 'Barangay 5 Nasugbu Batangas'),
            array('firstname' => 'Aya','middlename' => 'Ramirez','lastname' => 'Fernado','email' => 'aya.fernado.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-03-28','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Anthony','middlename' => 'Morales','lastname' => 'Borja','email' => 'anthony.borja.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-05-28','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Ace','middlename' => 'Mercado','lastname' => 'Magbanua','email' => 'ace.magbanua.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-11-02','address' => 'Poblacion 4, Calatagan Batangas'),
            array('firstname' => 'Jowel','middlename' => 'Tan','lastname' => 'DeCastro','email' => 'jowel.decastro.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-12-24','address' => 'Balibago, Calatagan Batangas'),
            array('firstname' => 'Ivan','middlename' => 'Aguilar','lastname' => 'Panganiban','email' => 'ivan.panganiban.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-04-24','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Ira','middlename' => 'Navarro','lastname' => 'Galang','email' => 'ira.galang.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1998-04-21','address' => 'Santa Ana, Calatagan Batangas'),
            array('firstname' => 'Wendy','middlename' => 'Manalo','lastname' => 'Roxas','email' => 'wendy.roxas.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-07-02','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Justin','middlename' => 'Gomez','lastname' => 'Ruiz','email' => 'justin.ruiz.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-09-05','address' => 'Barangay 12 Nasugbu Batangas'),
            array('firstname' => 'Ally','middlename' => 'Dizon','lastname' => 'Pangilinan','email' => 'ally.pangilinan.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-04-11','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Jericho','middlename' => 'Del Rosario','lastname' => 'Vicente','email' => 'jericho.vicente.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-02-21','address' => 'Barangay 6, Nasugbu Batangas'),
            array('firstname' => 'Carlos','middlename' => 'Javier','lastname' => 'Avila','email' => 'carlos.avila.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-05-30','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Mario','middlename' => 'Corpuz','lastname' => 'Austria','email' => 'mario.austria.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-05-27','address' => 'Barangay 10 Nasugbu Batangas'),
            array('firstname' => 'Erica','middlename' => 'Gutierrez','lastname' => 'Magno','email' => 'erica.magno.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-04-02','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Eric','middlename' => 'Salvador','lastname' => 'Dela Torre','email' => 'eric.dela torre.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-02-01','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Mico','middlename' => 'Velasco','lastname' => 'Luna','email' => 'mico.luna.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-07-11','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Jorge','middlename' => 'Mirando','lastname' => 'Pepito','email' => 'jorge.pepito.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-12-25','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Eduard','middlename' => 'David','lastname' => 'Solis','email' => 'eduard.solis.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-09-21','address' => 'Bagong Silong Calatagan Batangas'),
            array('firstname' => 'Gwen','middlename' => 'Salazar','lastname' => 'Duran','email' => 'gwen.duran.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-11-22','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Kimberly','middlename' => 'Alvarez','lastname' => 'Dela Rosa','email' => 'kimberly.dela rosa.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-04-26','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Marian','middlename' => 'Pacual','lastname' => 'Mahinay','email' => 'marian.mahinay.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-05-06','address' => 'Bucana Nasugbu Batangas'),
            array('firstname' => 'Sarah','middlename' => 'Lim','lastname' => 'Esguerra','email' => 'sarah.esguerra.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-10-06','address' => 'Wawa, Nasugbu Batangas'),
            array('firstname' => 'Lou','middlename' => 'Delos Reyes','lastname' => 'Roque','email' => 'lou.roque.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-07-04','address' => 'Barangay 8 Nasugbu Batangas'),
            array('firstname' => 'Paula','middlename' => 'Marquez','lastname' => 'Jose','email' => 'paula.jose.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-06-17','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Althea','middlename' => 'Jimenez','lastname' => 'Bonifacio','email' => 'althea.bonifacio.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-03-15','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'Sammy','middlename' => 'Cortez','lastname' => 'Beltran','email' => 'sammy.beltran.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '2000-06-10','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Jimmy','middlename' => 'Antonio','lastname' => 'Mateo','email' => 'jimmy.mateo.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-01-12','address' => 'Bulihan Nasugbu Batangas'),
            array('firstname' => 'John Dave','middlename' => 'Agustin','lastname' => 'Nicolas','email' => 'john dave.nicolas.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-10-14','address' => 'PutingKahoy Lian Batangas'),
            array('firstname' => 'Calvin','middlename' => 'Rosales','lastname' => 'Mendes','email' => 'calvin.mendes.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-07-10','address' => 'Binubusan Lian Batangas'),
            array('firstname' => 'Ashly','middlename' => 'Manuel','lastname' => 'Vasquez','email' => 'ashly.vasquez.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-12-20','address' => 'Barangay 1, Nasugbu Batangas'),
            array('firstname' => 'Alexander','middlename' => 'Sarmiento','lastname' => 'Lorenzo','email' => 'alexander.lorenzo.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-03-16','address' => 'Barangay 4, Nasugbu Batangas'),
            array('firstname' => 'Lourent','middlename' => 'Pascual','lastname' => 'Toledo','email' => 'lourent.toledo.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-11-19','address' => 'Dayap, Nasugbu Batangas'),
            array('firstname' => 'Casper','middlename' => 'Lim','lastname' => 'Marasigan','email' => 'casper.marasigan.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '2000-08-08','address' => 'Pandak na Duhat Nasugbu Batangas'),
            array('firstname' => 'Luis','middlename' => 'Enriquez','lastname' => 'Silva','email' => 'luis.silva.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1998-08-29','address' => 'Prenza Lian Batangas'),
            array('firstname' => 'Marco','middlename' => 'Ocampo','lastname' => 'Miguel','email' => 'marco.miguel.example@g.batstate-u.edu.ph','gender' => 'male','birthday' => '1999-06-24','address' => 'Biga, Calatagan, Batangas'),
            array('firstname' => 'Julia','middlename' => 'Alcantara','lastname' => 'Villa','email' => 'julia.villa.example@g.batstate-u.edu.ph','gender' => 'female','birthday' => '1999-03-15','address' => 'Prenza Lian Batangas')
        );

        foreach ($scholars as $key => $scholar) {
            $phone = '';
            $exists = true;
            while ( $exists ) {
                $phone = '09'.rand(100000000,999999999);
                $exists = User::where('phone', $phone)->exists();
            }

            User::factory()->create([
                'firstname' => $scholar['firstname'],
                'middlename' => $scholar['middlename'],
                'lastname' => $scholar['lastname'],
                'gender' => $scholar['gender'],
                'address' => $scholar['address'],
                'birthplace' => $scholar['address'],
                'phone' => $phone,
                'email' => $scholar['email'],
            ]);
        }
    }
}
